-- 002_import_products.sql
-- Import 44 products from old rentanje.com

INSERT INTO products (
  name, slug, category_id, short_desc, hero_image_url, images,
  min_rental_days, price_per_day, price_per_3days, price_per_7days,
  stock_qty, is_active, is_featured, sort_order
) VALUES
  ('Akcijska kamera GoPro Hero 10', 'akcijska-kamera-gopro-hero-10',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Snimaj avanture u 5.3K. Vodootporan, stabilan, lak za korištenje.', 'https://rentanje.com/wp-content/uploads/2022/08/Go-Pro.jpg', NULL,
   1, 15.0, 35.0, 65.0,
   1, 1::boolean, 0::boolean, 0),
  ('Plinska peč za pizzu OONI 16', 'plinska-pec-za-pizzu-ooni-16',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Ispeci savršenu pizzu do ⌀40cm u 60 sekundi. Plinski pogon, prijenosna.', 'https://rentanje.com/wp-content/uploads/2022/07/Oooni.webp', ARRAY["https://rentanje.com/wp-content/uploads/2023/11/Rentanje-background.jpg","https://rentanje.com/wp-content/uploads/2022/07/Ooni-pizza-16-4.webp","https://rentanje.com/wp-content/uploads/2022/07/Ooni-pizza-16-2.webp","https://rentanje.com/wp-content/uploads/2022/07/Ooni-pizza-16-1.webp","https://rentanje.com/wp-content/uploads/2022/07/Ooni-pizza-16.webp"]::text[],
   1, 40.0, 80.0, 120.0,
   1, 1::boolean, 0::boolean, 0),
  ('DJI Mavic Mini 2 fly more', 'dji-mavic-mini-2-fly-more',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Kompaktni dron s 4K kamerom, 31 min leta. Idealan za snimanje iz zraka.', 'https://rentanje.com/wp-content/uploads/2022/08/DJI-MINI-2.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2022/08/DJI-Mavic-Mini-2-fly-more-combo-1.webp","https://rentanje.com/wp-content/uploads/2022/08/DJI-Mavic-Mini-2-fly-more-combo-2.webp","https://rentanje.com/wp-content/uploads/2022/08/DJI-Mavic-Mini-2-fly-more-combo-3.webp","https://rentanje.com/wp-content/uploads/2022/08/DJI-Mavic-Mini-2-fly-more-combo.webp"]::text[],
   1, 30.0, 70.0, 160.0,
   1, 1::boolean, 0::boolean, 0),
  ('JBL Charge 3 prijenosni zvučnik', 'jbl-charge-3-prijenosni-zvucnik',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Vodootporni bluetooth zvučnik s 20h baterije. Zvuk koji puni atmosferu.', 'https://rentanje.com/wp-content/uploads/2022/08/JBL-Charge-3.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2022/08/JBL-Charge-3-3.jpg","https://rentanje.com/wp-content/uploads/2022/08/JBL-Charge-3-2.jpg","https://rentanje.com/wp-content/uploads/2022/08/JBL-Charge-3-1.jpg"]::text[],
   1, 20.0, 35.0, 65.0,
   1, 1::boolean, 0::boolean, 0),
  ('Ledomat', 'ledomat',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Proizvodi do 12 kg leda na dan. Savršen za evente, roštilj i outdoor zabave.', 'https://rentanje.com/wp-content/uploads/2024/03/Ledomat-1.jpeg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Ledomat-2.jpeg","https://rentanje.com/wp-content/uploads/2024/03/Ledomat.jpeg"]::text[],
   1, 25.0, 70.0, 110.0,
   1, 1::boolean, 0::boolean, 0),
  ('JBL Partybox', 'jbl-partybox',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Moćni party zvučnik s light show efektima. Punjiv, prenosiv.', 'https://rentanje.com/wp-content/uploads/2024/03/Partybox.jpg', NULL,
   1, 50.0, 125.0, 195.0,
   1, 0::boolean, 0::boolean, 0),
  ('Kotlovina -  73,5cm', 'kotlovina-735cm',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Tradicionalna kotlovina 73,5 cm. Za gulaš, čobanac i slavonske specijalitete.', 'https://rentanje.com/wp-content/uploads/2024/03/Kotlovina.jpg', NULL,
   1, 15.0, 30.0, 50.0,
   1, 1::boolean, 0::boolean, 0),
  ('Kotao od lijevanog željeza, 10 L, sa stalkom', 'kotao-od-lijevanog-zeljeza-10-l-sa-stalkom',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Lijevani kotlić 10L na stalku. Za autentični čobanac i varivo na vatri.', 'https://rentanje.com/wp-content/uploads/2024/03/Kotlic-za-cobanac.jpeg', NULL,
   3, NULL, 18.0, 30.0,
   1, 1::boolean, 0::boolean, 0),
  ('Baklja za roštilj', 'baklja-za-rostilj',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Propanska baklja za brzo paljenje roštilja. Precizni plamen, lagana.', 'https://rentanje.com/wp-content/uploads/2024/03/Rostilj-baklja.jpg', NULL,
   1, 20.0, 50.0, 84.0,
   1, 1::boolean, 0::boolean, 0),
  ('Peka/Sač', 'pekasac',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Kovana peka/sač za tradicijsko pečenje ispod žara. Idealna za meso i kruh.', 'https://rentanje.com/wp-content/uploads/2024/03/kovana-peka-2-scaled.jpg', NULL,
   1, 20.0, 50.0, 84.0,
   1, 1::boolean, 0::boolean, 0),
  ('Prenosivi ražanj s motorom', 'prenosivi-razanj-s-motorom',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Električni ražanj s motorom u torbi. Za prase, janjetinu i perad do 20 kg.', 'https://rentanje.com/wp-content/uploads/2024/03/Razanj-s-motorom.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/razanj-u-torbi-2.jpg","https://rentanje.com/wp-content/uploads/2024/03/razanj-u-torbi.jpg","https://rentanje.com/wp-content/uploads/2024/03/razanj-u-torbi-motor.jpg"]::text[],
   1, 50.0, 135.0, 210.0,
   1, 1::boolean, 0::boolean, 0),
  ('Točionik za pivo - 6L', 'tocionik-za-pivo-6l',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Točionik za pivo 6L s CO₂ hlađenjem. Svježe pivo na svakom eventu.', 'https://rentanje.com/wp-content/uploads/2024/03/Karlstein-tocionik-za-pivo.png', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/tocionik-za-pivo-3.webp","https://rentanje.com/wp-content/uploads/2024/03/tocionik-za-pivo-2.webp","https://rentanje.com/wp-content/uploads/2024/03/tocionik-za-pivo.webp"]::text[],
   1, 30.0, 80.0, 125.0,
   1, 1::boolean, 0::boolean, 0),
  ('Karaoke mašina sa 2 mikrofona', 'karaoke-masina-sa-2-mikrofona',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Karaoke set s 2 bežična mikrofona i zvučnikom. Zabava za cijelu obitelj.', 'https://rentanje.com/wp-content/uploads/2024/03/Karoke-mikrofon-i-zvucnik.jpg', NULL,
   1, 30.0, 80.0, 125.0,
   1, 0::boolean, 0::boolean, 0),
  ('Kokičar', 'kokicar',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Retro kokičar na vrući zrak. Savršen za kino večeri i dječje zabave.', 'https://rentanje.com/wp-content/uploads/2024/03/Kokicar.jpg', NULL,
   1, 5.0, 14.0, 20.0,
   1, 0::boolean, 1::boolean, 0),
  ('Firepit Bonfire 2.0.', 'firepit-bonfire-20',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Dizajnerski Bonfire 2.0 firepit. Topli ugođaj i savršena vatra za svako dvorište.', 'https://rentanje.com/wp-content/uploads/2024/03/Bonfire-2.0.webp', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/bonfire-2.0-fire-pit-4.jpg","https://rentanje.com/wp-content/uploads/2024/03/bonfire-2.0-fire-pit-3.jpg","https://rentanje.com/wp-content/uploads/2024/03/bonfire-2.0-fire-pit-2.jpg","https://rentanje.com/wp-content/uploads/2024/03/bonfire-2.0-fire-pit-1.jpg","https://rentanje.com/wp-content/uploads/2024/03/bonfire-2.0-fire-pit.jpg"]::text[],
   1, 50.0, 135.0, 210.0,
   1, 1::boolean, 0::boolean, 0),
  ('Velika Jenga', 'velika-jenga',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Giant Jenga za outdoor zabavu. Drveni blokovi, idealan za vrtove i terrase.', 'https://rentanje.com/wp-content/uploads/2024/03/Jenga.jpg', NULL,
   3, NULL, 8.0, 18.0,
   1, 1::boolean, 0::boolean, 0),
  ('Cornhole', 'cornhole',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Američka igra vrećicama. Zabava za sve generacije na picniku, vrtu ili plaži.', 'https://rentanje.com/wp-content/uploads/2024/03/Cornhole.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Cornhole-igra-5.avif","https://rentanje.com/wp-content/uploads/2024/03/Cornhole-igra-3.avif","https://rentanje.com/wp-content/uploads/2024/03/Cornhole-igra-2.avif","https://rentanje.com/wp-content/uploads/2024/03/Cornhole-igra.avif","https://rentanje.com/wp-content/uploads/2024/03/igra-cornhole.avif"]::text[],
   3, NULL, 10.0, 20.0,
   1, 1::boolean, 0::boolean, 0),
  ('Projektor sa platnom', 'projektor-sa-platnom',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'LG projektor Full HD + platno. Kino iskustvo pod zvijezdama u vašem vrtu.', 'https://rentanje.com/wp-content/uploads/2024/03/Projektor-s-platnom.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/LG-Beamer-PF50KS-projektor.jpg","https://rentanje.com/wp-content/uploads/2024/03/LG-Beamer-PF50KS.jpg","https://rentanje.com/wp-content/uploads/2024/03/LG-projektor.jpg","https://rentanje.com/wp-content/uploads/2024/03/platno-za-projektor-2.jpg","https://rentanje.com/wp-content/uploads/2024/03/platno-za-projektor-1.jpg"]::text[],
   1, 50.0, 135.0, 210.0,
   1, 1::boolean, 0::boolean, 0),
  ('Paviljon/Šator 3x3m', 'paviljonsator-3x3m',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Paviljon/šator 3x3m s UV zaštitom. Hlad i zaštita od kiše za vaš event.', 'https://rentanje.com/wp-content/uploads/2024/03/Sator-paviljon.webp', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Sator-paviljon-kolci.webp","https://rentanje.com/wp-content/uploads/2024/03/Sator-paviljon-1.webp","https://rentanje.com/wp-content/uploads/2024/03/Sator-paviljon.webp"]::text[],
   1, 25.0, 68.0, 105.0,
   1, 1::boolean, 0::boolean, 0),
  ('Prenosivi stol i 2 klupe za 8 osoba', 'prenosivi-stol-i-2-klupe-za-8-osoba',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Ratan stol + 2 klupe za 8 osoba. Praktično sjedenje za outdoor roštilj.', 'https://rentanje.com/wp-content/uploads/2024/03/Stol-i-2-klupe-za-8-osoba.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set-6.jpg","https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set-4.jpg","https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set-3.jpg","https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set-2.jpg","https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set-1.avif","https://rentanje.com/wp-content/uploads/2024/03/Ratan-pivski-set.avif"]::text[],
   1, 25.0, 68.0, 105.0,
   1, 1::boolean, 0::boolean, 0),
  ('Igloo Retro Jade 25 - piknik hladnjak', 'igloo-retro-jade-25-piknik-hladnjak',
   (SELECT id FROM categories WHERE slug = 'kamp-outdoor' LIMIT 1),
   'Retro piknik hladnjak 22L. Čuva temperaturu do 5 dana, bez struje.', 'https://rentanje.com/wp-content/uploads/2024/03/Igloo-piknik-hladnjak.png', NULL,
   1, 10.0, 27.0, 42.0,
   1, 0::boolean, 0::boolean, 0),
  ('RTIC 65 QT Ultra-Tough Cooler - 65L kamping hladnjak', 'rtic-65-qt-ultra-tough-cooler-65l-kamping-hladnjak',
   (SELECT id FROM categories WHERE slug = 'kamp-outdoor' LIMIT 1),
   'Premium kamping hladnjak 65L. Drži hladno do 5 dana, robustan.', 'https://rentanje.com/wp-content/uploads/2024/03/RTIC-65-QT-Ultra-Tough-Cooler-1.webp', NULL,
   1, 25.0, 68.0, 105.0,
   1, 0::boolean, 0::boolean, 0),
  ('Kamado roštilj', 'kamado-rostilj',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Keramički Kamado roštilj. Za dimljenje, pečenje i roštiljanje pri niskim i visokim temperaturama.', 'https://rentanje.com/wp-content/uploads/2024/03/Kamado-rostilj.jpg', NULL,
   1, 25.0, 68.0, 105.0,
   1, 0::boolean, 0::boolean, 0),
  ('Smoker roštilj s kutijom za dim', 'smoker-rostilj-s-kutijom-za-dim',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Smoker roštilj s kutijom za dim. Za American BBQ i brisket po recepturi.', 'https://rentanje.com/wp-content/uploads/2024/03/Beef-Brisket-rostilj-s-kutijom-za-dim.jpg', NULL,
   1, 25.0, 68.0, 105.0,
   1, 0::boolean, 0::boolean, 0),
  ('Roštilj na ugljen NAPOLEON NK22K-LEG-2', 'rostilj-na-ugljen-napoleon-nk22k-leg-2',
   (SELECT id FROM categories WHERE slug = 'rostilj-kuhanje' LIMIT 1),
   'Napoleon roštilj na ugljen. Kvalitetni čelik, podesiva visina roštilja.', 'https://rentanje.com/wp-content/uploads/2024/03/Rostilj-na-ugljen-NAPOLEON.jpg', NULL,
   1, 25.0, 68.0, 105.0,
   1, 0::boolean, 0::boolean, 0),
  ('Plutajući/svjetleći rozi flamingo', 'plutajucisvjetleci-rozi-flamingo',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Svjetleći rozi flamingo za bazen. Savršen dekor za pool party i ljetne zabave.', 'https://rentanje.com/wp-content/uploads/2024/03/Plutajuci-rozi-flamingo.jpg', NULL,
   1, 5.0, 14.0, 20.0,
   1, 0::boolean, 0::boolean, 0),
  ('Beerpong stol', 'beerpong-stol',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Profesionalni Beer Pong stol 240cm. Vodootporna površina, prenosiv.', 'https://rentanje.com/wp-content/uploads/2024/03/Beerpong.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Beerpong-3.webp","https://rentanje.com/wp-content/uploads/2024/03/Beerpong-2.webp","https://rentanje.com/wp-content/uploads/2024/03/Beerpong-1.webp","https://rentanje.com/wp-content/uploads/2024/03/Beerpong.webp"]::text[],
   3, NULL, 40.0, 60.0,
   1, 1::boolean, 0::boolean, 0),
  ('Solarni powerbank - 25000mAh', 'solarni-powerbank-25000mah',
   (SELECT id FROM categories WHERE slug = 'kamp-outdoor' LIMIT 1),
   'Solarni powerbank 25.000 mAh. Punjenje USB uređaja na svakom outdoor izletu.', 'https://rentanje.com/wp-content/uploads/2024/03/Hiluckey-solarni-Powerbank-25000mAh.jpg', NULL,
   1, 15.0, 41.0, 63.0,
   1, 0::boolean, 0::boolean, 0),
  ('Blumfeldt Dark Wave Infrared Grijalica', 'blumfeldt-dark-wave-infrared-grijalica',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Infracrvena grijalica 2000W. Topli outdoor prostor i do -10°C vani.', 'https://rentanje.com/wp-content/uploads/2024/03/Darwave-grijalia.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Blumfeldt-Dark-Wave-2.png","https://rentanje.com/wp-content/uploads/2024/03/Blumfeldt-Dark-Wave-1.png","https://rentanje.com/wp-content/uploads/2024/03/Blumfeldt-Dark-Wave.png"]::text[],
   1, 25.0, 68.0, 105.0,
   1, 1::boolean, 0::boolean, 0),
  ('JBL Partybox 310 BOX Bluetooth zvučnik na bateriju', 'jbl-partybox-310-box-bluetooth-zvucnik-na-bateriju',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'JBL PartyBox 310 — 240W, 18h baterije, light show. Pravi party zvučnik.', 'https://rentanje.com/wp-content/uploads/2024/03/Bluetooth-zvucnik-JBL-BT-BOX-310-2.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/03/Bluetooth-zvucnik-JBL-BT-BOX-310-1.jpg","https://rentanje.com/wp-content/uploads/2024/03/Bluetooth-zvucnik-JBL-BT-BOX-310-3.webp","https://rentanje.com/wp-content/uploads/2024/03/Bluetooth-zvucnik-JBL-BT-BOX-310.webp"]::text[],
   1, 40.0, 70.0, 100.0,
   1, 1::boolean, 0::boolean, 0),
  ('Kulinarski doživljaj', 'kulinarski-dozivljaj',
   (SELECT id FROM categories WHERE slug = 'ostalo' LIMIT 1),
   'Organiziramo kulinarski doživljaj s opremom, namirnicama i voditeljem.', 'https://rentanje.com/wp-content/uploads/2024/03/Kulirasko-iskustvo.jpg', NULL,
   1, 300.0, 600.0, 900.0,
   1, 1::boolean, 0::boolean, 0),
  ('Druženje na otvorenom', 'druzenje-na-otvorenom',
   (SELECT id FROM categories WHERE slug = 'ostalo' LIMIT 1),
   'Kompletan outdoor paket za nezaboravno druženje — oprema, hrana, zabava.', 'https://rentanje.com/wp-content/uploads/2024/03/Druzenje-na-otvorenom.jpg', NULL,
   1, 300.0, 600.0, 900.0,
   1, 1::boolean, 0::boolean, 0),
  ('Pizza party - Ooni Pizza Oven™', 'pizza-party-ooni-pizza-oven',
   (SELECT id FROM categories WHERE slug = 'ostalo' LIMIT 1),
   'Pizza party s Ooni pećnicom. Mi donosimo sve — tijesto, sastojke i opremu.', 'https://rentanje.com/wp-content/uploads/2024/03/Oooni-pizza-party.jpg', NULL,
   1, 300.0, 600.0, 900.0,
   1, 1::boolean, 0::boolean, 0),
  ('Sportski Spektakl', 'sportski-spektakl',
   (SELECT id FROM categories WHERE slug = 'ostalo' LIMIT 1),
   'Gledanje utakmice na velikom platnu s projektorom, zvukom i prigrizima.', 'https://rentanje.com/wp-content/uploads/2024/03/Gledanje-utakmice.jpg', NULL,
   1, 300.0, 600.0, 900.0,
   1, 1::boolean, 0::boolean, 0),
  ('Šator + 2 zračna madraca + električna pumpa - Najam', 'sator-2-zracna-madraca-elektricna-pumpa-najam',
   (SELECT id FROM categories WHERE slug = 'kamp-outdoor' LIMIT 1),
   'Šator za 4 osobe + 2 madraca + pumpa. Sve za udobno kampiranje.', 'https://rentanje.com/wp-content/uploads/2024/06/sator-za-kampiranje-sa-sipkama-arpenaz-42-f-b-4-osobe-2-sobe.avif', ARRAY["https://rentanje.com/wp-content/uploads/2024/06/kompaktna-i-punjiva-elektricna-pumpa-za-kampiranje-1.avif","https://rentanje.com/wp-content/uploads/2024/06/kompaktna-i-punjiva-elektricna-pumpa-za-kampiranje.avif","https://rentanje.com/wp-content/uploads/2024/06/madrac-na-napuhavanje-za-kampiranje-air-basic-140-cm-za-2-osobe.avif","https://rentanje.com/wp-content/uploads/2024/06/sator-za-kampiranje-sa-sipkama-arpenaz-42-f-b-4-osobe-2-sobe-1.avif"]::text[],
   3, NULL, 65.0, 110.0,
   1, 1::boolean, 0::boolean, 0),
  ('JBL Mikrofoni bežićni', 'jbl-mikrofoni-bezicni',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Bežični JBL mikrofoni za prezentacije, karaoke i eventi. Kompaktni i pouzdani.', 'https://rentanje.com/wp-content/uploads/2024/08/posnetek_zaslona_2024-05-13_150818.webp', NULL,
   1, 10.0, 20.0, 35.0,
   1, 1::boolean, 0::boolean, 0),
  ('DJI Neo Dron', 'dji-neo-dron',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'DJI Neo — najmanji DJI dron s 4K stabilizacijom. Lagan, brz, inovativan.', 'https://rentanje.com/wp-content/uploads/2024/09/najam-dji-neo.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2024/09/dji-neo-rentanje.jpg"]::text[],
   1, 25.0, 35.0, 50.0,
   1, 1::boolean, 0::boolean, 0),
  ('Stalak za kolače', 'stalak-za-kolace',
   (SELECT id FROM categories WHERE slug = 'oprema-za-evente' LIMIT 1),
   'Elegantni stalak za kolače i deserte. Savršen za svadbe, krštenja i proslave.', 'https://rentanje.com/wp-content/uploads/2024/10/WhatsApp-Image-2024-10-10-at-20.55.07-1-scaled.jpeg', ARRAY["https://rentanje.com/wp-content/uploads/2024/10/WhatsApp-Image-2024-10-10-at-20.55.08-scaled.jpeg","https://rentanje.com/wp-content/uploads/2024/10/WhatsApp-Image-2024-10-10-at-20.55.08-2-scaled.jpeg"]::text[],
   1, 30.0, 45.0, 55.0,
   1, 1::boolean, 0::boolean, 0),
  ('Fujifilm Instax mini EVO', 'fujifilm-instax-mini-evo',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'Fujifilm Instax Mini Evo — analogna kamera s Bluetooth printom. Trenutne uspomene.', 'https://rentanje.com/wp-content/uploads/2025/02/instax-evo-rentanje.webp', ARRAY["https://rentanje.com/wp-content/uploads/2025/02/instax-evo-mini-cijena.webp","https://rentanje.com/wp-content/uploads/2025/02/instanx-evo-mini-najam.webp"]::text[],
   1, 30.0, 40.0, 50.0,
   1, 1::boolean, 0::boolean, 0),
  ('Šator za kampiranje za 2 osobe - najam', 'sator-za-kampiranje-za-2-osobe-najam',
   (SELECT id FROM categories WHERE slug = 'kamp-outdoor' LIMIT 1),
   'Lagani šator za 2 osobe s blackout tehnologijom. Idealan za festivale i izlete.', 'https://rentanje.com/wp-content/uploads/2025/08/sator-za-kampiranje-mh100-fresh-black-za-tri-osobe.avif', ARRAY["https://rentanje.com/wp-content/uploads/2025/08/sator-za-kampiranje-mh100-fresh-black-za-tri-osobe-2.avif","https://rentanje.com/wp-content/uploads/2025/08/sator-za-kampiranje-mh100-fresh-black-za-tri-osobe-1.avif","https://rentanje.com/wp-content/uploads/2025/08/madrac-na-napuhavanje-za-kampiranje-air-basic-140-cm-za-2-osobe.avif","https://rentanje.com/wp-content/uploads/2025/08/elektricna-pumpa-za-kampiranje-punjiva-pomocu-uscb-c-kabela.avif"]::text[],
   7, NULL, NULL, NULL,
   1, 0::boolean, 0::boolean, 0),
  ('Kamera sa gimbal stabilizatorom', 'kamera-sa-gimbal-stabilizatorom',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'DJI Osmo Pocket 3 s 3-osnim gimbaloom. 4K60 video, savršen za vloganje.', 'https://rentanje.com/wp-content/uploads/2025/09/osmo_pocket_3_creator_combo.2.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2025/09/osmo_pocket_3-08_1.png","https://rentanje.com/wp-content/uploads/2025/09/osmo_pocket_3-07_1.png"]::text[],
   7, NULL, NULL, NULL,
   1, 0::boolean, 0::boolean, 0),
  ('Kärcher usisavač za dubinsko pranje - najam', 'krcher-usisavac-za-dubinsko-pranje-najam',
   (SELECT id FROM categories WHERE slug = 'alati-ciscenje' LIMIT 1),
   'Kärcher Puzzi za dubinsko čišćenje tepiha, tapecirung i sjedala auta.', 'https://rentanje.com/wp-content/uploads/2025/09/d1.jpg', ARRAY["https://rentanje.com/wp-content/uploads/2025/09/d1-2.jpg","https://rentanje.com/wp-content/uploads/2025/09/d1-3.jpg","https://rentanje.com/wp-content/uploads/2025/09/d1-4.jpg"]::text[],
   7, NULL, NULL, NULL,
   1, 0::boolean, 0::boolean, 0),
  ('Prijenosni zvučnik JBL PartyBox za najam', 'prijenosni-zvucnik-jbl-partybox-za-najam',
   (SELECT id FROM categories WHERE slug = 'audio-video-oprema' LIMIT 1),
   'JBL PartyBox Stage 320 — 240W, IPX4, prijenosni. Za outdoor nastupe.', 'https://rentanje.com/wp-content/uploads/2025/09/JBL_PARTYBOX_STAGE_320_HERO_2_47988_x3.webp', ARRAY["https://rentanje.com/wp-content/uploads/2025/09/JBL_PARTYBOX_STAGE_320_TOP_48066_x1.webp"]::text[],
   7, NULL, NULL, NULL,
   1, 0::boolean, 0::boolean, 0);